### ISSUE TITLE
Redmi K30S Ultra It doesn't work

### ISSUE THREAD

**Issue by moluyang** [Whyle/android_device_xiaomi_apollo#1]
Thank you for your effort

**Comment by Whyle** [comment]
Can you tell me howw it doesn't work? Not boot? Stuck?
----
还是不能进入Twrp

**Comment by moluyang** [comment]
> ## 你能告诉我怎么不起作用吗？不是启动？卡住了？
> _ twrp

刷入之后不能进入twrp 直接跳入fastboot

**Comment by moluyang** [comment]
> > ## 你能告诉我怎么不起作用吗?不是启动?卡住了?
> > _ twrp
> 
> [twrp] 快速启动

可以加我，我可以帮助调试

**Comment by Whyle** [comment]
hey, How can I contact you...
